"""
Agent Reliability Lab — Core Package.

Exports the complete domain model, state machine, and error hierarchy.
All entities use strict Pydantic v2 validation with no defaults that
could mask missing data.
"""

from arl.core.domain import (
    AgentDefinition,
    AgentTurn,
    AgentVersion,
    AuditEvent,
    Baseline,
    Budget,
    Environment,
    EnvironmentVersion,
    EvaluationRun,
    Evidence,
    ExpectedEffect,
    FaultEvent,
    FaultPlan,
    ForbiddenEffect,
    Grader,
    GraderResult,
    GraderVersion,
    ModelConfiguration,
    Project,
    Regression,
    Report,
    Scenario,
    ScenarioVersion,
    SecurityFinding,
    ToolCall,
    ToolDefinition,
    ToolResult,
    Trial,
    WorldStateSnapshot,
)
from arl.core.errors import (
    ARLError,
    BudgetExceededError,
    ConcurrentModificationError,
    ConfigurationError,
    DomainError,
    DuplicateEffectError,
    EvidenceError,
    FaultInjectionError,
    ForbiddenEffectDetectedError,
    GradingError,
    InfrastructureError,
    InvalidStateTransitionError,
    IsolationViolationError,
    ScenarioValidationError,
    SecurityViolationError,
    TerminalStateImmutableError,
    UnauthorizedError,
    WorkerLeaseError,
)
from arl.core.state_machine import (
    EvaluationRunState,
    EvaluationRunStateMachine,
    StateTransition,
)

__all__ = [
    # Errors
    "ARLError",
    # Domain entities
    "AgentDefinition",
    "AgentTurn",
    "AgentVersion",
    "AuditEvent",
    "Baseline",
    "Budget",
    "BudgetExceededError",
    "ConcurrentModificationError",
    "ConfigurationError",
    "DomainError",
    "DuplicateEffectError",
    "Environment",
    "EnvironmentVersion",
    "EvaluationRun",
    # State machine
    "EvaluationRunState",
    "EvaluationRunStateMachine",
    "Evidence",
    "EvidenceError",
    "ExpectedEffect",
    "FaultEvent",
    "FaultInjectionError",
    "FaultPlan",
    "ForbiddenEffect",
    "ForbiddenEffectDetectedError",
    "Grader",
    "GraderResult",
    "GraderVersion",
    "GradingError",
    "InfrastructureError",
    "InvalidStateTransitionError",
    "IsolationViolationError",
    "ModelConfiguration",
    "Project",
    "Regression",
    "Report",
    "Scenario",
    "ScenarioValidationError",
    "ScenarioVersion",
    "SecurityFinding",
    "SecurityViolationError",
    "StateTransition",
    "TerminalStateImmutableError",
    "ToolCall",
    "ToolDefinition",
    "ToolResult",
    "Trial",
    "UnauthorizedError",
    "WorkerLeaseError",
    "WorldStateSnapshot",
]
