"""
Agent Reliability Lab — Trial and WorldStateSnapshot Domain Entities.
"""

from __future__ import annotations

import enum
from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field


class TrialStatus(str, enum.Enum):
    """Execution status of a single trial."""

    PENDING = "pending"
    CLAIMED = "claimed"  # worker has claimed this trial
    RUNNING = "running"
    GRADING = "grading"
    COMPLETED = "completed"
    FAILED = "failed"
    TIMED_OUT = "timed_out"
    CANCELLED = "cancelled"
    UNKNOWN = "unknown"  # worker crashed — outcome not determined


class TrialVerdict(str, enum.Enum):
    """Deterministic grading verdict for a trial.

    PASS: All deterministic checks passed.
    FAIL: One or more deterministic checks failed.
    CRITICAL_FAIL: A critical failure (forbidden effect, isolation violation, etc.).
    GRADER_ERROR: The grader itself encountered an error.
    INSUFFICIENT_EVIDENCE: Not enough data to grade.
    """

    PASS = "PASS"
    FAIL = "FAIL"
    CRITICAL_FAIL = "CRITICAL_FAIL"
    GRADER_ERROR = "GRADER_ERROR"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class Trial(BaseModel):
    """A single independent execution of a scenario.

    Multiple trials per run enable statistical analysis (pass@k, etc.).

    Worker idempotency: trial_index + run_id + idempotency_key must be
    unique. Workers that claim the same trial twice must be detected and
    the duplicate discarded.

    Security note: Trial state is authoritative from PostgreSQL. Redis
    only delivers work item references, never authoritative state.
    """

    model_config = {"frozen": True}

    id: str = Field(..., description="Stable ULID trial identifier")
    run_id: str = Field(..., description="Parent EvaluationRun ID")
    trial_index: int = Field(..., ge=0, description="Zero-based trial index within the run")
    idempotency_key: str = Field(
        ...,
        description=(
            "Worker idempotency key. A worker that sees this key twice "
            "must discard the duplicate without creating a new trial."
        ),
    )
    worker_id: str | None = Field(
        default=None,
        description="ID of the worker that claimed this trial",
    )
    lease_expires_at: datetime | None = Field(
        default=None,
        description="Worker lease expiry — lost leases are recoverable",
    )
    status: TrialStatus = Field(default=TrialStatus.PENDING)
    verdict: TrialVerdict | None = Field(
        default=None,
        description="Grading verdict. None until grading is complete.",
    )

    # Metrics — populated after completion
    turn_count: int | None = Field(default=None, ge=0)
    tool_call_count: int | None = Field(default=None, ge=0)
    total_tokens: int | None = Field(default=None, ge=0)
    total_cost_usd: float | None = Field(default=None, ge=0.0)
    duration_ms: int | None = Field(default=None, ge=0)

    # Timing
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    claimed_at: datetime | None = Field(default=None)
    started_at: datetime | None = Field(default=None)
    completed_at: datetime | None = Field(default=None)

    # Failure
    failure_reason: str | None = Field(
        default=None,
        description="Human-readable failure reason. Must not contain secrets.",
    )
    failure_code: str | None = Field(default=None)

    # Random seed for this specific trial's fault injection
    fault_seed: int = Field(
        ...,
        description=(
            "Deterministic seed for this trial's fault schedule. "
            "Derived from run seed + trial_index."
        ),
    )

    metadata: dict[str, str] = Field(default_factory=dict)


class WorldStateSnapshot(BaseModel):
    """A captured snapshot of the environment world state at a point in time.

    Used by graders to verify expected and forbidden effects.
    Snapshots are taken before and after trial execution.

    The snapshot format is environment-specific. The 'state' field is
    a free-form dict validated by the environment's snapshot schema.

    Security note: snapshot content is generated by the environment
    (trusted), not by the agent (untrusted). Path traversal in JMESPath
    expressions is limited to read-only evaluation.
    """

    model_config = {"frozen": True}

    id: str = Field(..., description="Stable ULID snapshot identifier")
    trial_id: str
    environment_version_id: str
    snapshot_type: str = Field(
        ...,
        description="Type: 'initial' (before trial) or 'final' (after trial)",
        pattern=r"^(initial|final|checkpoint)$",
    )
    state: dict[str, Any] = Field(
        ...,
        description=(
            "Environment world state at snapshot time. "
            "Structure is environment-version specific and schema-validated."
        ),
    )
    captured_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    schema_version: str = Field(..., description="Environment snapshot schema version")
    is_schema_valid: bool = Field(
        ...,
        description="Whether this snapshot passed schema validation at capture time",
    )
