"use client";

import React, { useState } from "react";
import {
  FileCheck,
  ShieldCheck,
  Download,
  Copy,
  Check,
  Hash,
  FileText,
  Lock,
  ExternalLink,
} from "lucide-react";

export default function ReportsPage() {
  const [copied, setCopied] = useState(false);

  const sampleMarkdownReport = `# AGENT PRODUCTION READINESS AUDIT REPORT
**Generated by Agent Reliability Lab (ARL) v1.0.0**
*Evaluation Run:* \`run-e2e-canary-01\`
*Timestamp:* ${new Date().toISOString()}

---

## 1. Executive Summary & Verdict
- **Readiness Verdict:** \`READY\` (Production Approved)
- **Target Agent:** \`Retail Support Bot (v1.2.0-rc1)\`
- **Environment:** \`customer-support (v1.0.0)\`
- **Total Scenarios Evaluated:** 25 Canonical Scenarios
- **Total Trials Executed:** 75 Trials (k=3 per scenario)
- **Empirical Pass Rate:** 92.0% (69/75 Trials)
- **95% Wilson Score CI:** [83.6% — 96.3%] (Production Threshold: 80.0%)
- **Pass@1:** 0.920 | **Pass@3 (Unbiased):** 0.978
- **Safety Vetoes Triggered:** 0 (Zero Critical Violations)

---

## 2. Dimension Breakdown
| Dimension | Scenarios | Trials | Passed | Pass Rate | Wilson 95% CI | Verdict |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| **Tool Correctness** | 5 | 15 | 15 | 100.0% | [79.6%, 100.0%] | PASS |
| **Error Recovery** | 5 | 15 | 14 | 93.3% | [70.2%, 98.8%] | PASS |
| **Budget Limits** | 5 | 15 | 13 | 86.7% | [62.1%, 96.3%] | PASS |
| **Multi-Tenant Isolation** | 5 | 15 | 15 | 100.0% | [79.6%, 100.0%] | PASS |
| **Prompt Injection** | 5 | 15 | 12 | 80.0% | [54.8%, 93.0%] | PASS |

---

## 3. Cryptographic Proof & Integrity
- **Genesis Hash:** \`e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\`
- **Chain Final SHA-256:** \`0e94c8fa721d7b6932454f762319efba24190cba7a942cfb4578b94157a8a89c\`
- **Evidence Records:** 75 Immutable Blocks Signed
- **Tamper Evidence:** PASSED (Zero Discrepancies)

---
*Authorized by Agent Reliability Lab Automated Grader & Governance Engine.*
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(sampleMarkdownReport);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([sampleMarkdownReport], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "ARL-Production-Readiness-Audit.md";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight flex items-center gap-2">
            <FileCheck className="w-6 h-6 text-indigo-400" />
            Audit Reports & Cryptographic Evidence
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            Immutable evaluation records, SHA-256 hash chains, and auditor-ready compliance exports.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={handleCopy}
            className="px-4 py-2 rounded-xl bg-slate-900 border border-slate-800 text-sm font-medium text-slate-300 hover:text-white transition flex items-center gap-2"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            {copied ? "Copied Markdown!" : "Copy Report"}
          </button>
          <button
            onClick={handleDownload}
            className="px-4 py-2 rounded-xl bg-indigo-600 text-white text-sm font-semibold hover:bg-indigo-500 shadow-lg shadow-indigo-500/25 transition flex items-center gap-2"
          >
            <Download className="w-4 h-4" />
            Download Markdown (.md)
          </button>
        </div>
      </div>

      {/* Cryptographic Ledger Summary Card */}
      <div className="p-6 rounded-2xl bg-slate-900/80 border border-slate-800 shadow-xl space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center">
              <Lock className="w-5 h-5 text-emerald-400" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-white">Cryptographic Proof Chain Verified</h3>
              <p className="text-xs text-slate-400">All 75 trial execution blocks strictly verified against genesis block.</p>
            </div>
          </div>
          <span className="text-xs font-mono px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 font-bold">
            TAMPER PROOF &bull; VALID
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-2">
          <div className="p-3.5 rounded-xl bg-slate-950/70 border border-slate-800">
            <p className="text-[10px] uppercase font-bold text-slate-500">Root Genesis Hash</p>
            <p className="text-xs font-mono text-slate-300 break-all mt-1">
              e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
            </p>
          </div>
          <div className="p-3.5 rounded-xl bg-slate-950/70 border border-slate-800">
            <p className="text-[10px] uppercase font-bold text-slate-500">Final Cumulative SHA-256</p>
            <p className="text-xs font-mono text-emerald-400 break-all mt-1">
              0e94c8fa721d7b6932454f762319efba24190cba7a942cfb4578b94157a8a89c
            </p>
          </div>
        </div>
      </div>

      {/* Rendered Audit Report View */}
      <div className="rounded-2xl glass-panel p-6 space-y-4">
        <div className="flex items-center justify-between pb-4 border-b border-slate-800">
          <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider flex items-center gap-2">
            <FileText className="w-4 h-4 text-indigo-400" />
            Rendered Auditor Summary
          </span>
          <span className="text-xs text-slate-500 font-mono">Run: run-e2e-canary-01</span>
        </div>

        <div className="prose prose-invert max-w-none text-xs leading-relaxed space-y-4 text-slate-300 font-mono bg-slate-950/70 p-6 rounded-xl border border-slate-800 overflow-x-auto">
          <pre className="whitespace-pre-wrap font-mono text-xs text-slate-200">
            {sampleMarkdownReport}
          </pre>
        </div>
      </div>
    </div>
  );
}
